fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending

  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.2.0
    hooks:
    - id: fmt
    - id: check
    - id: clippy
    - id: test
